### ISSUE TITLE
Can I use it with the ffmpeg running with subprocess?

### ISSUE THREAD

**Issue by Akascape** [jonghwanhyeon/python-ffmpeg#14]
I have used my ffmpeg code like this with the simple **subprocess** method:

```python
subprocess.call(f'"{ffmpeg}" -i "{input_path}" {parameters} -y "{output_path}"', shell=True)
```

But I want to get and use the events like progress, termination etc with that **running instance** of ffmpeg. 

How can I do that with python-ffmpeg? Thanks in advance :)

**Comment by jonghwanhyeon** [comment]
Hello,

To track progress from ffmpeg, we need to pipe `stdout` of ffmpeg process to your process and parse them. And this library does that instead of users.

Unfortunately, these bunch of processes cannot be easily applied to manually spawned ffmpeg process.

If you really need to track the progress of manually spawned ffmpeg, you have to do the above process by yourself.
