### ISSUE TITLE
ffprobe not showing full metadata of files

### ISSUE THREAD

**Issue by zbrasseaux** [jonghwanhyeon/python-ffmpeg#67]
```
ffprobe = FFmpeg(executable="ffprobe").input(
	args.input_file,
	print_format = "json",
	show_streams = None
)

```

I am using the above to read in the metadata of a file, however, I am only getting the technical metadata about my audio file.
I am looking for data such as artist, album title, chapters, etc. I would like to use the chapters timestamp data in order to programmatically split the file.

I have searched the documentation (where I found the above code) and have not seen anything that would give me additional data. Any help is appreciated.

**Comment by HunterAP23** [comment]
You'll want to run one of these commands:
`ffprobe -print_format json -show_entries format_tags=track YOUR_FILE_HERE.mp3` which translates to:
```
ffprobe = FFmpeg(executable="ffprobe").input(
	args.input_file,
	print_format = "json",
	show_entries = "format_tags=track"
)
```

or with FFmpeg instead of FFprobe it would be `ffmpeg -i YOUR_FILE_HERE.mp3 -f ffmetadata -` which would translate to:
```
ffprobe = FFmpeg(executable="ffmpeg").input(args.input_file).output(
	"-"
	f = "ffmetadata",
)
```
You'll want to parse the bytes stdout of those commands to get the data you want though

**Comment by zbrasseaux** [comment]
this works, thank you.
